# -*- coding: utf-8 -*-
"""netflix.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bYZ_p914IFnFzM7gAUjoziGnpKw1Nl-t
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('netflix_titles.tsv', sep='\t')
df.head()

df.shape

df['type'].unique()

df['type'].value_counts()

len(df['country'].unique())

l=dict(df['country'].value_counts()[:21])
print(l)
list_pays=list(l.keys())

print(list_pays)

df.isna().sum()

df.isna().sum()

for s in df['country']:
  try:
    s=str(s) 
  except:
    print(s)

pays=list_pays
print(pays)



contenu=['']*len(pays)
dictionn=dict(zip(pays,contenu))
print(dictionn)


for c in pays:
  datapays=df[df['country']==c]
  for p in datapays['listed_in']:
    dictionn[c] +=str(p)


print(dictionn)

pays_centenu=[]
for key, values in dictionn.items():
    pays_centenu.append([key,values])



output1=[]
output2=[]
output3=[]
for i in range(21):
    output2+=[pays_centenu[i][0]]
    output3+=[pays_centenu[i][1]]
d={'pays':output2,'contenu':output3}

df_pays = pd.DataFrame(d)
df_pays.index += 1 
df_pays

